baseURL = 'https://royalvarez.dev/'
languageCode = 'en-us'
title = 'Roy Codes'
theme = "ghostwriter"

[params]
mainSections = ["post"]
intro = true
headline = "Welcome to my website"
description = "A blog exploring all things programming"

[menu]
  [[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2


github = "https://github.com/royalvarez"
email = "hello@royalvarez.dev"

opengraph = true

dateFormat = "Thursday, September 24, 2026"